# .github/workflows/main.yml

name: AI News Feeder

on:
  workflow_dispatch: # 수동으로 실행할 수 있도록 설정
  schedule:
    - cron: '0 22 * * *' # 매일 22:00 UTC (한국 시간 기준 다음 날 오전 7시)에 실행

jobs:
  build-and-send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 파이썬 버전 지정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to send email
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          NCLOUD_ACCESS_KEY: ${{ secrets.NCLOUD_ACCESS_KEY }}
          NCLOUD_SECRET_KEY: ${{ secrets.NCLOUD_SECRET_KEY }}
          NCLOUD_SENDER_ADDRESS: ${{ secrets.NCLOUD_SENDER_ADDRESS }}
          MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          EMAIL_SENDER_TYPE: ${{ vars.EMAIL_SENDER_TYPE }}
          DEFAULT_EMAIL_TEMPLATE: ${{ vars.DEFAULT_EMAIL_TEMPLATE }}
          RECIPIENTS: ${{ vars.RECIPIENTS }}
          SENDER_NAME: ${{ vars.SENDER_NAME }}
          NEWS_ARTICLE_COUNT: ${{ vars.NEWS_ARTICLE_COUNT }}
        run: python main.py --notify teams
